export enum HelpTypeEnum {
    DEPENDENT = 'DEPENDENTE',
    INDEPENDENT = 'INDEPENDENTE',
    POSITIONAL = 'POSICIONAL',
    GESTURE = 'GESTUAL',
    VERBAL = 'VERBAL',
    PHYSICAL = 'FÍSICA',
    VISUAL = 'VISUAL',
    NOT_EXECUTED = 'NÃO EXECUTADO'
}