export interface IStudent {
  id: string,
  fullname: string,
  birthday: Date | null,
  document: string,
  allergy: string,
  genere: string,
  indentity_number: string | null,
  nationality: string | null,
  org_exp: string | null,
  uf_exp: string | null,
  phone: string | null,
  email: string | null,
  avatar: string | null,
  status: string | null,
}

export interface IResponsable {
  id?: string | null,
  company_id?: string | null,
  fullname: string,
  birthday: Date | null,
  document: string,
  indentity_number: string | null,
  nationality: string | null,
  org_exp: string | null,
  uf_exp: string | null,
  phone: string | null,
  email: string | null,
  main_contract: string | null,
  bond: string | null,
  main: string | null,
  status: string | null,
}